# Generated by Django 5.1.4 on 2025-06-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_length", models.PositiveSmallIntegerField(default=12)),
                ("col_length", models.PositiveSmallIntegerField(default=12)),
                ("grid_checked", models.BooleanField(default=False)),
                (
                    "inProgress",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("initial_time", models.DateTimeField(blank=True, null=True)),
                ("finished_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("word_checked", models.BooleanField(default=False)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="wordsearch.puzzle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Char",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=1)),
                ("index", models.PositiveSmallIntegerField()),
                ("char_checked", models.BooleanField(default=False)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chars",
                        to="wordsearch.puzzle",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chars",
                        to="wordsearch.word",
                    ),
                ),
            ],
        ),
    ]
