# Generated by Django 5.2.1 on 2025-06-18 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NonUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="wordsearch", max_length=20, null=True
                    ),
                ),
                ("row_length", models.PositiveSmallIntegerField(default=12)),
                ("col_length", models.PositiveSmallIntegerField(default=12)),
                ("grid_checked", models.BooleanField(default=False)),
                (
                    "inProgress",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("initial_time", models.DateTimeField(blank=True, null=True)),
                ("finished_time", models.DateTimeField(blank=True, null=True)),
                (
                    "nonuser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wordsearch.nonuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("word_checked", models.BooleanField(default=False)),
                ("word_color", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="wordsearch.puzzle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Char",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=1)),
                ("index", models.PositiveSmallIntegerField()),
                ("char_checked", models.BooleanField(default=False)),
                ("char_color", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chars",
                        to="wordsearch.puzzle",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chars",
                        to="wordsearch.word",
                    ),
                ),
            ],
        ),
    ]
