# Generated by Django 5.2.1 on 2025-06-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="char",
            name="word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chars",
                to="wordsearch.word",
            ),
        ),
    ]
