# Generated by Django 5.1.4 on 2025-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0002_alter_char_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="inProgress",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
