# Generated by Django 5.1.4 on 2025-06-06 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0002_puzzle_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="puzzle",
            name="non_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wordsearch.nonuser",
            ),
        ),
    ]
