# Generated by Django 5.1.4 on 2025-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0003_puzzle_inprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="time_elapsed",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
