# Generated by Django 5.1.4 on 2025-06-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0003_nonuser_puzzle_non_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="puzzle",
            old_name="non_user",
            new_name="nonuser",
        ),
    ]
