# Generated by Django 5.1.4 on 2025-06-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0004_puzzle_time_elapsed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="time_elapsed",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="finished_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="initial_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
