# Generated by Django 5.1.4 on 2025-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0004_rename_non_user_puzzle_nonuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="word_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
