# Generated by Django 5.1.4 on 2025-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0005_word_word_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="char",
            name="char_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
