# Generated by Django 5.1.4 on 2025-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsearch", "0005_remove_puzzle_time_elapsed_puzzle_finished_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="finished_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="initial_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
