# Generated by Django 5.2.1 on 2025-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="sudoku", max_length=10)),
                ("challenge", models.JSONField()),
                ("solution", models.JSONField()),
                ("is_solved", models.BooleanField(default=False)),
            ],
        ),
    ]
