# Generated by Django 5.2.1 on 2025-06-13 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudokuapp", "0001_initial"),
        ("wordsearch", "0006_char_char_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="finished_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="inProgress",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="initial_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="nonuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sudoku_puzzles",
                to="wordsearch.nonuser",
            ),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sudoku_puzzles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
