# Generated by Django 5.2.1 on 2025-06-14 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudokuapp", "0002_puzzle_finished_time_puzzle_inprogress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_value", models.PositiveIntegerField(blank=True, null=True)),
                ("cell_index", models.PositiveSmallIntegerField()),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="sudokuapp.puzzle",
                    ),
                ),
            ],
        ),
    ]
